### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [stuartcalder/3crypt#1]
Dear @stuartcalder,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?,

**Comment by stuartcalder** [comment]
I could. Give me some time and I will produce a Windows binary.

**Comment by stuartcalder** [comment]
Sorry for taking so long but I had a number of issues with my Windows VM. This is a statically compiled 3crypt binary.
I plan on finalizing V1 of 3crypt and its libraries soon but until then you can use this.
[3crypt.exe.zip](https://github.com/stuartcalder/3crypt/files/6247724/3crypt.exe.zip)

**Comment by sergeevabc** [comment]
@stuartcalder, not sure which RNG was used here, but be sure to look at [PCG][1]. For example, [MKRandom][2] use it.

[1]: https://www.pcg-random.org/
[2]: https://github.com/Tinram/mkrandom/tree/c_legacy/bin

**Comment by sergeevabc** [comment]
And, in general, it would be great to know more about the local encoding scheme. So far I see 512-bit mentioned and that’s all.
In practice, it’s too slow for daily use (compared to symmetric encryption of Age, Kryptor, Minilock, Triops, and GPG Twofish256).

**Comment by stuartcalder** [comment]
@sergeevabc
We use the [Threefish-512](https://en.wikipedia.org/wiki/Threefish) tweakable block cipher in counter-mode for symmetric encryption, and the [Skein](https://en.wikipedia.org/wiki/Skein_hash_function) hash function as an RNG, MAC, and memory-hard key derivation function. Skein is built out of Threefish, and its specification provides proof that Skein is a cryptographically secure hash function (when Threefish is modeled as an ideal block cipher). We use the [Catena](https://www.password-hashing.net/submissions/specs/Catena-v5.pdf) Password Hashing Framework, which is a generic framework for memory-hard password hashing. In 3crypt we use Catena to harden encrypted files against brute force attack. Assuming Catena is sound, brute force guessing attacks against passwords are significantly thwarted.
You mentioned that the default settings are slow: yes. By default, 3crypt is much slower than for example GPG using Twofish256.
3crypt is also much stronger than GPG using Twofish256. I believe GPG accomplishes key derivation for symmetric encryption through simple repeated hashing. It is theoretically orders of magnitude harder to brute-force a 3crypt-encrypted file versus a GPG-encrypted file, when using the same password for both.
Right now 3crypt defaults to consuming 1GiB of memory for key-derivation. For most file sizes, deriving a cryptographic key from your given password takes much longer than the encryption itself. Try using '--use-memory 512m' to use 512 MiB of memory for key-derivation instead of 1GiB for faster encryption/decryption, but less protection against attack.

**Comment by sergeevabc** [comment]
@stuartcalder
Thank you for explanation. I’m glad Threefish and Skein are finally in demand. One day, perhaps, someone will even try Lyra2 for key derivation to compete with Argon 2id (of Keepass, for example). As for `--use-memory 512m`, still it takes unacceptable 15–20 seconds on my rig. And nothing to date convinces me that such a resource-intensive investment is justified in any way against the daily threat model, so in my opinion your undertaking is rather an academic experiment at best or security LARPing at worst I’ll stay with 7z, CryptFS, GPG, and Age for symmetric encryption, because they manage to provide a usability balance.

**Comment by stuartcalder** [comment]
@sergeevabc 
It is rather academic, but I don't think that makes it LARPing.
What are your hardware specs?

I've tested the speed of GPG symmetrically encrypting a 2.1GiB file in a tmpfs ramdisk on Linux,
each time with the password 'password' and averaging the time of two tests.

AES128: about 3.9 seconds.
AES256: about 4.5 seconds.
Twofish256: about 11.5 seconds.

3crypt using 1GiB: about 17.8 seconds.
3crypt using 512MiB: about 12.15 seconds.
3crypt using 256MiB: about 9.15 seconds.
3crypt using 128MiB: about 7.7 seconds.
